server:
  port: 8001
  servlet:
    context-path: /movies/

spring:
  application:
    name: movie-service
  zipkin:
    base-url: http://zipkin-service:9411/
  datasource:
    url: jdbc:mysql://localhost:3307/db_movies
    username: root
    password: mauFJcuf5dhRMQrjj
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true

eureka:
  instance:
    hostname: eureka-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mensagem: hello world

management:
  endpoints:
    web:
      exposure:
        include: '*'
