#server:
#  port: 8002
#  servlet:
#    context-path: /catalog/

spring:
  application:
    name: catalog-service
#  zipkin:
#    base-url: http://zipkin-service:9411/
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      username: root
      password: rootpassword
      port: 27017
      host: localhost
      database: db_series
  config:
    import: optional:configserver:http://config-server:8888/
  cloud:
    config:
      profile: dev
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
queue:
  movie:
    name: MovieQueue

eureka:
  instance:
    hostname: eureka-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mensagem: hello catalog

management:
  endpoints:
    web:
      exposure:
        include: '*'
