version: '3.1'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.1
    ports:
      - '8080:8080'
      - '9091:9091'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
